global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hand-gesture-api'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']